version: '3.8'

services:
  app:
    build: .
    ports:
      - "8080:8080"
    environment:
      - ENVIRONMENT=production
      - SERVER_PORT=8080
      - DATABASE_PATH=/app/burgers.db
      - REDIS_ADDR=redis:6379
    depends_on:
      - redis
    volumes:
      - ./app/static:/app/app/static  # монтируем статику

  redis:
    image: redis:7-alpine