# config/app.yaml
environment:
  current: "development" 

server:
  port: ":8080"
  cookiesecure: false

database:
  path: "./burgers.db"

redis:
  addr: "localhost:6379"
  password: ""
  db: 0

jwt:
  secretkey: "ultra_super_strong_secret_key_XFJ12JTPM"

ratelimit:
  maxrequests: 100
  window: 1m 

email:
  smtHost: "smtp.gmail.com"
  smtPort: "587"
  username: "soldathekler@gmail.com"
  password: "mxoj jbcr qsaz huhb"
  from: "Horizon Messenger <soldathekler@gmail.com>"