CREATE TABLE IF NOT EXISTS users (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    username TEXT NOT NULL UNIQUE,
    passwordHash TEXT NOT NULL,
    email TEXT NOT NULL UNIQUE,
    is_verified BOOLEAN DEFAULT FALSE,
    verify_token VARCHAR(255)
)